name = "lared809"
main = "worker.js"
compatibility_date = "2024-03-04"

[triggers]
crons = []

[site]
bucket = "./"

[build]
command = "echo 'No build step required'"
cwd = "."

[env.production]
name = "lared809-lottery"
route = "lared809.com/*" 