name = "lared809-lottery"
main = "./worker.js"
compatibility_date = "2024-03-04"

[site]
bucket = "./"

[build]
command = "echo 'No build step required'"
cwd = "."

[env.production]
name = "lared809-lottery"
route = "lared809.com/*" 