name = "lared809-lottery"
main = "worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./"

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "lared809-lottery"
route = "lared809.com/*" 