name = "lared809"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2024-03-04"

[triggers]
crons = []

[site]
bucket = "./public"
entry-point = "worker.js"

[build]
command = "echo 'No build step required'"
cwd = "."

[env.production]
name = "lared809-lottery"
route = "lared809.com/*" 